#MP3 TO SHEET MUSIC PROJECT
#Description: This project takes in an MP3 file and then makes sheet music either including vocals or only background music.
#Name : Sam Taju Ninan
#Date Created: June 30th
#Last modified: September 5th

from basic_pitch.inference import predict_and_save #Spotify's ML model for transcribing audio to MIDI
import demucs.separate #Meta's stem separation model for isolating vocals/instruments
from basic_pitch import ICASSP_2022_MODEL_PATH #path to the specific basic_pitch model weights file
from music21 import converter, clef #music notation library. converter parses MIDI, clef sets staff clefs, stream handles score structure
import pretty_midi #MIDI manipulation library used for harmonic filtering and beat quantization
import librosa #audio analysis library used for tempo detection and beat tracking
import subprocess #opens MuseScore 4 from Python
from pathlib import Path #handles file paths cleanly across operating systems
import tempfile #creates a temporary working directory that is deleted after the program ends
import os #used to access /dev/null for suppressing basic-pitch debug output
import sys #used to redirect stdout to silence basic-pitch debug print statements

def separate_stems(mp3_path, output_dir, keep_vocals=True):
    """
    Description: Uses Demucs to separate vocals and instruments into separate audio files
    Pre-Condition: MP3 path should be pointing to a proper mp3 file, and output_dir should be there as well.
    Post-Condition: Separates the stems and returns the file path to either the vocals or no_vocals stem as an MP3,
    :param mp3_path: The path to the inputted MP3 file
    :param output_dir: Directory where Demucs will save the separated stems
    :param keep_vocals: If True, it returns the vocal stem (which includes background music). If false, it returns the instrumental only.
    :return: String path to the selected stem MP3 file.
    """
    demucs.separate.main(["--mp3", "--two-stems", "vocals", "-o", output_dir, mp3_path])
    song_name = Path(mp3_path).stem
    #choose stem based on parameter that is there
    if keep_vocals:
        stem = "vocals.mp3"  #se the vocal melody line
    else:
        stem = "no_vocals.mp3"  #use the instrumental/piano
    return str(Path(output_dir) / "htdemucs" / song_name / stem)

def transcribe_to_midi(audio_path, output_dir):
    """
    Description: uses Spotify's basic pitch pre-trained neural network to transcribe audio into a MIDI file.
    Pre-Condition: audio_path must point to a valid audiofile. output_dir must exist.
    Post-Condition: A MIDI file is saved to output_dir and its path is returned
    :param audio_path: path to the inputted audio file (MP3 ONLY: WAV files not tested yet)
    :param output_dir: Directory where the MIDI file will be saved
    :return: Path object pointing to the generated MIDI file
    """
    with open(os.devnull, 'w') as devnull:
        old_stdout = sys.stdout
        sys.stdout = devnull
        # silences all print output during prediction
        predict_and_save(
            [audio_path],
            # list of input audio paths
            output_dir,
            True,  # save_midi
            False,  # sonify_midi (don't need a WAV rendering)
            False,  # save_model_outputs
            False,  # save_notes
            minimum_frequency=65,  # low C on piano (C2)
            maximum_frequency=1047,  # high C on piano (C6)
            model_or_model_path=ICASSP_2022_MODEL_PATH,  # tells basic-pitch which model to use
        )
        sys.stdout = old_stdout  # restores normal output afterward
    midi_path = Path(output_dir) / f"{Path(audio_path).stem}_basic_pitch.mid"  # constructs the file path for a MIDI file
    return midi_path

def remove_harmonics(midi_path, output_dir):
    """
    Description: Filters out harmonic overtones from the MIDI file that basic pitch shows as notes. (CONTINUED IN NEXT LINE)
    Usually same notes in different octaves are detected to be there, so this function takes the lowest note since many "high" notes are detected more frequently.
    Pre-Condition: midi_path must point to a valid MIDI file, output_dir must exist.
    Post-Condition: A cleaned MIDI file with harmonics is saved to output_dir and its path is returned
    :param midi_path: Path to the MIDI file generated by basic-pitch
    :param output_dir: Directory where the cleaned MIDi file will be saved
    :return: Path object pointing to the cleaned MIDI file.
    """
    # loads the MIDI basic pitch generated
    pm = pretty_midi.PrettyMIDI(str(midi_path))

    # the following code takes the midi and removes any note where the same pitch class exists an octave lower at the same moment
    for instrument in pm.instruments:
        # Sort notes by start time
        notes = sorted(instrument.notes, key=lambda n: n.start)
        filtered = []
        for i, note in enumerate(notes):
            # Check if a note an octave below is playing at the same time
            is_harmonic = any(
                (note.pitch - other.pitch) in [12, 24, 19] and  #octave, two octaves, or fifth
                abs(other.start - note.start) < 0.05
                for other in notes
                if other.pitch < note.pitch  #only check notes LOWER than current note
            )
            if not is_harmonic:
                filtered.append(note)
        instrument.notes = filtered

    # Save the cleaned MIDI
    clean_midi_path = Path(output_dir) / "clean.mid"
    pm.write(str(clean_midi_path))
    return clean_midi_path

def quantize_to_beats(midi_path, audio_path, output_dir):
    """
    Description: Puts the notes onset times to the nearest detected beat using librosa beat tracking
    Pre-Condition: midi_path must point to a valid MIDI file, audio_path must point to the original audio
    Post-Condition: A beat quantized MIDI is saved to output_dir and its path is returned
    :param midi_path: path to the cleaned MIDI file from remove_harmonics()
    :param audio_path: Path to the audio file used to detect beats
    :param output_dir: directory where the quantized MIDI file will be saved
    :return: path object pointing to the beat quantized MIDI file
    """
    y, sr = librosa.load(audio_path)
    tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr) #get tempo and beat positions
    beat_times = librosa.frames_to_time(beat_frames, sr=sr) #convert frame indices to seconds

    #Load the MIDI and snap each note to the nearest beat
    pm = pretty_midi.PrettyMIDI(str(midi_path))

    for instrument in pm.instruments:
        for note in instrument.notes:
            #Find the closest beat time to this note's onset
            closest_beat = min(beat_times, key=lambda b: abs(b - note.start))

            #Snap the note start to that beat
            note.start = closest_beat

            #Recalculate note end using the original duration
            original_duration = note.end - note.start  # save duration BEFORE changing start
            note.start = closest_beat  # snap to beat
            note.end = note.start + original_duration  # recalculate end using saved duration

        #Save the quantized MIDI
    quantized_midi_path = Path(output_dir) / "quantized.mid"
    pm.write(str(quantized_midi_path))
    return quantized_midi_path

def generate_score(midi_path, output_dir):
    """
    Description: Converts a MIDI file into sheet music notation and opens it in MuseScore 4 (it also corrects any wrong clefs in the music)
    Pre-Condition: midi_path must point to a valid MIDI file, MuseScore 4 must be installed
    Post-Condition: A quantized MIDI file is saved to output_dir and opened in MuseScore 4
    :param midi_path: Path to the cleaned MIDI file
    :param output_dir: Directory where the final MIDI file will be saved
    :return: music21 score object containing the full notation
    """
    score = converter.parse(str(midi_path))  #loads the MIDI file into a music21 Score object

    #Detects key from the score and apply it
    detected_key = score.analyze('key')
    score.insert(0, detected_key)  #sets the correct key signature on the score

    #Forces treble clef on top staff, bass clef on bottom staff
    for i, part in enumerate(score.parts):
        #Collect all existing clefs in this part
        clefs_to_remove = list(part.recurse().getElementsByClass(clef.Clef))

        #Safely remove them from their parent containers
        for c in clefs_to_remove:
            c.activeSite.remove(c)

        #Target the first measure
        first_measure = part.measure(1)
        if first_measure is None:
            first_measure = part.getElementsByClass("Measure").first()

        #Insert the correct clef at beat 0 OUTSIDE the removal loop
        if i == 0:
            first_measure.insert(0, clef.TrebleClef())
        else:
            first_measure.insert(0, clef.BassClef())

    #Quantize note durations to a 16th note grid
    score = score.quantize(quarterLengthDivisors=[4])  #4 divisions per quarter note = 16th note grid
    midi_out = Path(output_dir) / "output.mid"
    score.write('midi', fp=str(midi_out))  # export final MIDI
    subprocess.run(['open', '-a', 'MuseScore 4', str(midi_out)])  # open in MuseScore
    return score

def extract_properties(score, mp3_path):
    """
    Description: Takes and prints the musical properties of the score
    Pre-Condition: score must be a proper music21 Score object, mp3_path must point to the valid mp3 file
    Post-Condition: Prints key, time signature, tempo, and duration (printed directly into the console)
    :param score: music21 score object generated by generate_score()
    :param mp3_path: Path to the original MP3 file used for duration and tempo analysis
    :return: Null
    """
    key = score.analyze('key')  # Finds the key
    time_sigs = score.getTimeSignatures()  # Finds Time Signature
    duration = librosa.get_duration(path=str(mp3_path))  # gets how long the song is

    print(f"Key: {key.tonic.name.replace('-', 'b')} {key.mode}")  # Prints the key

    if time_sigs:  # prints the time signature
        print(f"Time Signature: {time_sigs[0].numerator}/{time_sigs[0].denominator}")
    else:  # if not able to find time signature
        print("Unknown")

    #Load the audio as a waveform
    y, sr = librosa.load(mp3_path)  # y is the audio signal, sr is sample rate (usually 22050 Hz)

    # Detect tempo from the waveform
    tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)  #beat_frames

    print(f"Tempo: {round(float(tempo))} BPM")  #tempo is returned as an array, so take first element

    print(f"Duration: {int(duration // 60)}m {int(duration % 60)}s")  # Prints duration

def main():

    mp3_path = '/Users/samtaju/Downloads/Für Elise Right Hand Melody.mp3'
    output_dir = tempfile.mkdtemp()  #makes a temporary file that is deleted once the /Users/samtaju/Downloads/Soprogram is finished

    print("Separating stems...")
    clean_audio = separate_stems(mp3_path, output_dir, keep_vocals=False)  # set True for vocals

    print("Transcribing to MIDI...")
    midi_path = transcribe_to_midi(clean_audio, output_dir)

    print("Removing harmonics...")
    midi_path = remove_harmonics(midi_path, output_dir)

    print("Quantizing to beats...")
    midi_path = quantize_to_beats(midi_path, clean_audio, output_dir)  # use clean_audio not mp3_path

    print("Generating score...")
    score = generate_score(midi_path, output_dir)

    print("Extracting properties...")
    extract_properties(score, mp3_path)

if __name__ == "__main__": #just a precauion: to only un this script when the file is being run directly.
    main()

